name: Pre-release

on:
  push:
    tags:
      - 'v*.*.*-pre*'

jobs:
  build:
    uses: ./.github/workflows/build.yml

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v4

    - name: Zip Artifacts
      run: |
        zip -r CasparLauncher_SelfContained_x64.zip CasparLauncher_SelfContained_x64
        zip -r CasparLauncher.zip CasparLauncher
    
    - name: Create Pre-release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        name: Pre-release ${{ github.ref_name }}
        prerelease: true
        files: |
          CasparLauncher.zip
          CasparLauncher_SelfContained_x64.zip
